Implemented menu screen
AndroidMentorship/android-mentorship-app pull request #10
Opened 2018-05-05 10:37 UTC by princessdharmy

2018-05-05 10:52 UTC, helios66 requested changes
Fix the issues and I'll merge into the dev branch.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/MenuActivity.java
> +public class MenuActivity extends BankingAppBaseActivity {
Rename `BankingAppBaseActivity` to `TinyGameAppBaseActivity`

2018-05-05 10:52 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/presenter/menuactivity/MenuActivityPresenter.java
> + */
Always remove this header comment.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/res/drawable/single_player_button.xml
> +                        android:endColor="@color/SPButtonShadow"
`sp_button_shadow` for variables inside xml.
`aButton` camel case for variables inside Java.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/res/layout-land/activity_menu.xml
> +        android:layout_width="354dp"
`@dimen/default_button_width` make this a dimension.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/res/layout-land/activity_menu.xml
> +        android:background="@drawable/multi_player_button"
Consider making the button a layout and using include layout.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/res/values/colors.xml
> +    <color name="SPButtonGreenDark">#33174C16</color>
The naming convention for variables in xml.

2018-05-05 10:52 UTC, helios66 commented on app/src/main/res/values/strings.xml
> +    <string name="title_activity_main_menu">MainMenuActivity</string>
Make variables alphabetical.

2018-05-05 15:22 UTC, princessdharmy commented
@helios66 all changes have been made except the `include` button that could not be manipulated in the XML code

2018-05-06 14:48 UTC, helios66 approved these changes
This is dope!

2018-05-06 14:48 UTC, merged