Implement Splash screen
AndroidMentorship/android-mentorship-app pull request #11
Opened 2018-05-11 12:04 UTC by Noel-96

What does this PR do?
 This PR creates both the splash screen and the quote screen.

How should this be manually tested?
This should be tested by running the application  on your device or in an emulator

Additional Information? 
I used a Tablet to test the application so apologies  if the screenshot makes it look like the spacing is off

Screenshots :

![screenshot_2018-06-02-07-16-50](https://user-images.githubusercontent.com/20171941/40915727-0e4f2a22-67f5-11e8-8dc1-e216b63ae4cb.png)
![screenshot_2018-06-02-07-16-55](https://user-images.githubusercontent.com/20171941/40915735-14b6c6c2-67f5-11e8-900a-1ce50ccc3396.png)

2018-05-19 09:13 UTC, helios66 requested changes

2018-05-19 09:13 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity.java
> +    private static int SPLASH_TIME_OUT = 3000;
Views should be inflated using ButterKnife, not findViewById.

Have a look at how to use butterknife. It's already part of the project.

2018-05-19 09:13 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity.java
> +        mSplashText = (TextView) findViewById(R.id.splash_text_id);
This line isn't needed of you're using butterknife.

2018-05-19 09:13 UTC, helios66 commented on app/src/main/res/values/styles.xml
> +
These lines aren't needed. Remove them.

2018-05-19 09:13 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity.java
> +
This can introduce a memory leak. Create a Handler variable instead and set to null ondestroy of the activity.

2018-06-04 12:58 UTC, helios66 requested changes
Great job! Please attend to comments.

2018-06-04 12:58 UTC, helios66 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".activities.Splash_Screen_Activity"
Remove `_` from naming convention for classes.

2018-06-04 12:58 UTC, helios66 commented on app/src/main/AndroidManifest.xml
> +
Remove extra spaces.

2018-06-04 12:58 UTC, helios66 commented on app/src/main/AndroidManifest.xml
> +                  android:screenOrientation="portrait"
Remove `_`

2018-06-04 12:58 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity.java
> +
remove extra spaces.

2018-06-04 12:58 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity.java
> +                startActivity(i);
Move this segment of code into the Coordinator class.

2018-06-04 12:58 UTC, helios66 commented on app/src/main/java/com/am/fdamilola/bankingapp/activities/Splash_Screen_Activity_2.java
> +                "fonts/nats-regular.ttf");
Font type can be defined inside xml. Look into that.

2018-06-04 12:59 UTC, helios66 commented
@Noel-96 please, properly format the PR comment. You just need a screenshot of the screen not of your IDE. 😄

2018-06-05 13:14 UTC, helios66 approved these changes

2018-06-05 13:14 UTC, merged

2018-06-06 11:06 UTC, Noel-96 commented
forgot to add the QuoteScreenActivityPresenter and QuoteScreenActivityPresenterImpl classes